// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMKEQbgxnkO4fEq5q5eEvNIaPwlDF0Ypk',
    appId: '1:1028021030959:web:dab319e667e69f40f3b6da',
    messagingSenderId: '1028021030959',
    projectId: 'flutterfirebase-98eed',
    authDomain: 'flutterfirebase-98eed.firebaseapp.com',
    storageBucket: 'flutterfirebase-98eed.appspot.com',
    measurementId: 'G-9HMJYBNSLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQnLvNFDtXyu1Mrd36DAjX-pQR---2hQ',
    appId: '1:1028021030959:android:78863f767e6a1d2df3b6da',
    messagingSenderId: '1028021030959',
    projectId: 'flutterfirebase-98eed',
    storageBucket: 'flutterfirebase-98eed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk4939S4LJTLfGlWiDMIX27HtLOvJfJMk',
    appId: '1:1028021030959:ios:52e71abcfc4fd5b1f3b6da',
    messagingSenderId: '1028021030959',
    projectId: 'flutterfirebase-98eed',
    storageBucket: 'flutterfirebase-98eed.appspot.com',
    iosClientId: '1028021030959-lca6a7tscigooccoet0gmicg9l1tp13q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
